server:
    port: 8080

rabbitmq:
    services:
        - host: localhost # 192.168.25.1
          port: 5672
    username: guest
    password: guest
    topic:
    queue-to-receive: habr
    routing-key-to-receive: habr
