server:
  port: 8080

rabbitmq:
  services:
    - host: localhost # 192.168.25.1
      port: 5672
  username: guest
  password: guest
  topic: ch-topic-exchange
  queue-to-receive: ch-queue
  routing-key-to-receive: ch-routing-key
