server:
  port: 8080

constants:
  admin:
    email: admin@jobhunter.com
    login: admin
    password: admin
  vacancies-heartbeat-url: http://localhost:8081/vacancies/heartbeat
  statistics-heartbeat-url: http://localhost:8082/statistics/heartbeat

rabbitmq:
  services:
    - host: localhost # 192.168.25.1
      port: 5672
  username: guest
  password: guest
  topic: jh-topic-exchange
  queue-to-send0: jh-queue-to-vacancies
  queue-to-send1: jh-queue-to-statistics
  queue-to-send2: jh-queue-to-vacancies-cancel
  queue-to-receive0: jh-queue-to-aggregator-vacancies
  queue-to-receive1: jh-queue-to-aggregator-statistics
  routing-key-to-send0: jh-routing-key-to-vacancies
  routing-key-to-send1: jh-routing-key-to-statistics
  routing-key-to-send2: jh-routing-key-to-vacancies-cancel
  routing-key-to-receive0: jh-routing-key-to-aggregator-vacancies
  routing-key-to-receive1: jh-routing-key-to-aggregator-statistics

spring:
  application:
    name: aggregator

  datasource:

    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


#  liquibase:
  #    url: jdbc:postgresql://localhost:5434/test_db
  #    user: postgres
  #    password: postgres
  #    change-log: liquibase/db.changelog-master.yaml
  #    enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: shadaevlab7@gmail.com
    password: ojoc jbuk uejc almi
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true