server:
  port: 8081

rabbitmq:
  services:
    - host: localhost
      port: 5672
  username: guest
  password: guest
  topic: jh-topic-exchange
  queue-to-send: jh-queue-to-aggregator-vacancies
  queue-to-receive0: jh-queue-to-vacancies
  queue-to-receive1: jh-queue-to-vacancies-cancel
  routing-key-to-send: jh-routing-key-to-aggregator-vacancies
  routing-key-to-receive0: jh-routing-key-to-vacancies
  routing-key-to-receive1: jh-routing-key-to-vacancies-cancel

websites:
  habr:
#    num-of-elements: 25
    num-of-elements-per-page: 25
  hh:
#    num-of-elements: 50
    num-of-elements-per-page: 50
  rabota:
#    num-of-elements: 30
    num-of-elements-per-page: 30
